simple loop for episode_list links
luk27official/ivysilani-mpd-extractor pull request #1
Opened 2024-06-28 14:22 UTC by Omelug

Když je url odkaz na seznam epizod, projde postupně všechny

2024-06-29 16:16 UTC, luk27official requested changes
Ahoj, diky moc za prispeni, jestli ti to nevadi, tak poprosim jeste doopravit tyhle malickosti - pokud se ti to nebude chtit delat, tak mi to jen napis a udelam to nekdy ja. K jednotlivym radkum jsem pridal komenty.

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +import os
```suggestion

```
Tohle prosim hodit k tem knihovnam o par radku dolu (at jde videt, ze jde o standardni, jako time, json apod. :)

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +    title = f"{folder}{title}"
```suggestion
    title = os.path.join(folder, title)
```

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +    #check if the URL is link to epizode list or only one epizode
```suggestion
    # check if the URL is a link to an episode list or only one episode
```

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +    if re.match(r"https://www.ceskatelevize.cz/[^/]*/[^/]*/$", url):
```suggestion
    if re.match(EPISODES_LIST_REGEX, url):
```
Tady prosim neco takoveho a hodit to do tech konstant nahore treba jako EPISODES_LIST_REGEX - pak kdyz se neco ma menit, tak staci upravovat na jednom miste nahore a je to rychlejsi

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +        print(f"Get infro from episode list {url}")
```suggestion
        print(f"Get info about the episode list {url}")
```

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +                more_button = chrome.find_element(By.CLASS_NAME, 'moreButton-0-2-141')
```suggestion
                more_button = chrome.find_element(By.CLASS_NAME, MORE_BTN_CLASSNAME)
```
To stejne jako nahore - do konstant pls

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +                WebDriverWait(chrome, 10).until(EC.element_to_be_clickable((By.CLASS_NAME, 'moreButton-0-2-141')))
```suggestion
                WebDriverWait(chrome, MORE_VIDEOS_LOAD_TIME).until(EC.element_to_be_clickable((By.CLASS_NAME, MORE_BTN_CLASSNAME)))
```
To stejne + i pro cisla to je fajn delat

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +                WebDriverWait(chrome, 5)
```suggestion
                WebDriverWait(chrome, MORE_VIDEOS_LOAD_TIME2)
```

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +        episodeListSection = chrome.find_element(By.ID, 'episodeListSection')
```suggestion
        episodeListSection = chrome.find_element(By.ID, EPISODE_LIST_CLASSNAME)
```

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +        elements = episodeListSection.find_elements(By.CLASS_NAME, "ctco_1gy3thf4")
```suggestion
        elements = episodeListSection.find_elements(By.CLASS_NAME, ??)
```
Tady vlastne ani nejak nevim, co se tam selectuje, kdyztak k tomu vymysli nejaky nazev :D

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +            os.makedirs(folder)
```suggestion
        folder_title = chrome.title.replace("/", "_").replace("\\", "_").replace(" ", "_")
        matches = re.findall(r'[\w]', folder_title)
        folder_title = ''.join(matches) + "/"
        os.makedirs(folder_title, exist_ok=True)
```
To vytvoreni slozky jde zkratit, coz je spis malickost, ale hlavne k tomu titlu - kdyz to jeste nematchnes regexem nebo nejak nesanitizujes, tak mi to nefunguje `OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './Most - iVysílání | Česká televize/'`

2024-06-29 16:16 UTC, luk27official commented on extract.py
> +    #chrome.quit()
Tady moc nerozumim proc to je zakomentovane, vadilo to necemu? 🤔

2024-06-30 19:59 UTC, Omelug commented
Díky za opravu, snad by to už mělo být ok, když tak napiš

2024-06-30 20:10 UTC, luk27official commented
Ahoj, jeste to musis pushnout k sobe do forku, abych to videl :-)

2024-07-02 18:08 UTC, luk27official approved these changes

2024-07-02 18:08 UTC, luk27official commented
lgtm, diky moc :) 🚀

2024-07-02 18:09 UTC, merged